import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",

// eg: for title metadata - also add it any other folder when it need .. allow to separately add absolute default template
  /*title :{
     default:"jfkfkoefkoekof",
     template:"%s | jfeofkoef",
     absolute:"hugjrpogokgt"
  }   */
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
